name: RDP-Ubuntu

on:
  workflow_dispatch:

jobs:
  rdp-ubuntu:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: Update & Install Desktop + XRDP
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y ubuntu-desktop xrdp
          
          # enable XRDP service
          sudo systemctl enable xrdp
          sudo systemctl start xrdp
          
          # allow port 3389 (optional, Tailscale will handle internally)
          sudo ufw allow 3389/tcp || true

      - name: Create RDP user
        run: |
          USERNAME=rdpuser
          PASSWORD=$(openssl rand -base64 12)
          sudo useradd -m -s /bin/bash $USERNAME
          echo "$USERNAME:$PASSWORD" | sudo chpasswd
          echo "RDP_USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "RDP_PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} --hostname=gh-runner-${GITHUB_RUN_ID}

      - name: Get Tailscale IP
        run: |
          TS_IP=$(tailscale ip -4 | head -n 1)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: Print Connection Info
        run: |
          echo "======================================"
          echo "🖥️  RDP to Ubuntu Runner"
          echo "IP Address  : $TAILSCALE_IP"
          echo "Username    : $RDP_USERNAME"
          echo "Password    : $RDP_PASSWORD"
          echo "======================================"

      - name: Keep session alive
        run: |
          while true; do
            echo "[$(date)] RDP Active on $TAILSCALE_IP"
            sleep 300
          done
