name: XRDP-KaliLinux

on:
  workflow_dispatch:

jobs:
  kali-xrdp:
    runs-on: ubuntu-latest
    timeout-minutes: 3600

    steps:
      - name: 🛠️ Update & Convert to Kali-like Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg lsb-release
          echo "deb http://http.kali.org/kali kali-rolling main non-free contrib" | sudo tee /etc/apt/sources.list.d/kali.list
          wget -q -O - https://archive.kali.org/archive-key.asc | sudo apt-key add -
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y
          sudo apt-get install -y kali-linux-core kali-tools-top10 xfce4 xfce4-goodies xorg dbus-x11 x11-xserver-utils xrdp

          sudo systemctl enable xrdp
          sudo systemctl restart xrdp

      - name: 👤 Create XRDP User
        run: |
          USERNAME=kaliuser
          PASSWORD=$(openssl rand -base64 12)
          sudo useradd -m -s /bin/bash $USERNAME
          echo "$USERNAME:$PASSWORD" | sudo chpasswd
          sudo usermod -aG sudo $USERNAME

          echo xfce4-session > /home/$USERNAME/.xsession
          sudo chown $USERNAME:$USERNAME /home/$USERNAME/.xsession

          echo "XRDP_USERNAME=$USERNAME" >> $GITHUB_ENV
          echo "XRDP_PASSWORD=$PASSWORD" >> $GITHUB_ENV

      - name: 💾 Setup Swap (2GB)
        run: |
          sudo fallocate -l 2G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab
          echo "✅ Swap 2GB aktif"

      - name: 🌐 Install & Connect Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up --authkey=${{ secrets.TAILSCALE_AUTH_KEY }} \
                            --hostname=kali-xrdp-${GITHUB_RUN_ID} \
                            --ssh --accept-dns=true --accept-routes=true

      - name: 📡 Get Tailscale IP
        run: |
          TS_IP=$(tailscale ip -4 | head -n 1)
          echo "TAILSCALE_IP=$TS_IP" >> $GITHUB_ENV

      - name: 💻 Print XRDP Access Info
        run: |
          echo "======================================"
          echo "🐉 Kali Linux XRDP Session"
          echo "IP Address : ${{ env.TAILSCALE_IP }}"
          echo "Username   : ${{ env.XRDP_USERNAME }}"
          echo "Password   : ${{ env.XRDP_PASSWORD }}"
          echo "======================================"
          echo "👉 Akses dengan RDP Client (Windows/macOS/Linux):"
          echo "Server: ${{ env.TAILSCALE_IP }}"
          echo "Username: ${{ env.XRDP_USERNAME }}"
          echo "Password: ${{ env.XRDP_PASSWORD }}"
          echo "======================================"
          echo "⚙️ Swap RAM sudah aktif otomatis (2GB)"

      - name: 🕓 Keep session alive
        run: |
          while true; do
            echo "[$(date)] Kali XRDP Active on ${{ env.TAILSCALE_IP }}"
            sleep 300
          done
